import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <h1>Medium Clone</h1>
       <h2>This is to practice</h2>
       <ul>
        <li>Next</li>
        <li>Github</li>
        <li>Vercel</li>
        <li>Firebase</li>
        <li>Formik</li>
        <li>MaterialUI</li>
       </ul>
      </main>
    </>
  )
}
